#### Camada Semântica e Inteligência de Negócio (Views e Queries)
Este notebook consolida a etapa final do projeto de Data Warehouse. 
1. Criar **Views Semânticas** no PostgreSQL para cada Tabela Fato. Isso desnormaliza os dados, facilitando a conexão com ferramentas de BI (Power BI, Metabase) sem expor a complexidade dos JOINs.
2. Executar as **12 Queries Estratégicas** definidas no `README.md` do projeto, validando o poder analítico da modelagem dimensional construída.

In [1]:
import importlib.util
import subprocess
import sys

REQUIRED_PACKAGES = {
    'pandas': 'pandas',
    'numpy': 'numpy',
    'sqlalchemy': 'sqlalchemy',
    'psycopg2': 'psycopg2-binary',
}

missing_packages = [
    package_name
    for module_name, package_name in REQUIRED_PACKAGES.items()
    if importlib.util.find_spec(module_name) is None
]

if missing_packages:
    print('Instalando dependencias ausentes:', ', '.join(missing_packages))
    subprocess.check_call([sys.executable, '-m', 'pip', 'install', *missing_packages])
else:
    print('Dependencias ja instaladas.')

Dependencias ja instaladas.

In [2]:
import os
import pandas as pd
from sqlalchemy import create_engine, text

# 1. Configuração da Conexão com o Data Warehouse
DB_URI = os.getenv('DB_URI', 'postgresql+psycopg2://admin:senha_segura_123@localhost:5433/dw_academico')
engine = create_engine(DB_URI)

try:
    with engine.connect() as conn:
        res = conn.execute(text("SELECT version();")).fetchone()
        print(f"Conexão bem-sucedida ao DW!\nMotor: {res[0]}")
except Exception as e:
    print(f"Erro de conexão: {e}")

Conexão bem-sucedida ao DW!
Motor: PostgreSQL 16.14 on x86_64-pc-linux-musl, compiled by gcc (Alpine 15.2.0) 15.2.0, 64-bit

#### Passo 1: Deploy das Views Semânticas (Data Mart Layer)
Criaremos 4 Views (Vendas, Logística, Pagamentos e Satisfação). Elas traduzem as Surrogate Keys (`sk_`) em dimensões descritivas, entregando "tabelões" prontos para consumo de negócio.

In [3]:
# DDL das Views Semânticas
views_sql = """
-- 1. VIEW DE VENDAS
CREATE OR REPLACE VIEW vw_semantica_vendas AS
SELECT 
    fv.sk_vendas, fv.dd_order_id, fv.dd_order_item_id,
    c.bk_customer_unique_id, c.customer_state, c.customer_city,
    p.product_category_name_english AS categoria,
    fv.preco_item, fv.valor_frete, fv.valor_total_item,
    t.ano, t.mes, t.trimestre
FROM fato_vendas fv
JOIN dim_cliente c ON fv.fk_cliente = c.sk_cliente
JOIN dim_produto p ON fv.fk_produto = p.sk_produto
JOIN dim_tempo t ON fv.fk_tempo = t.sk_tempo;

-- 2. VIEW DE LOGÍSTICA (PLACEHOLDER - tabela não existe ainda)
CREATE OR REPLACE VIEW vw_semantica_logistica AS
SELECT 
    0 as dd_order_id,
    '' as estado_destino,
    '' as bk_seller_id,
    0 as dias_em_transito, 
    0 as dias_totais_entrega, 
    0 as dias_atraso, 
    0 as flag_atrasado,
    2024 as ano, 
    1 as trimestre
WHERE FALSE;

-- 3. VIEW DE PAGAMENTOS (PLACEHOLDER - tabela não existe ainda)
CREATE OR REPLACE VIEW vw_semantica_pagamentos AS
SELECT 
    0 as dd_order_id,
    '' as bk_customer_unique_id,
    0::NUMERIC as valor_pagamento, 
    0 as parcelas_pagamento,
    '' as forma_pagamento,
    2024 as ano, 
    1 as mes
WHERE FALSE;

-- 4. VIEW DE SATISFAÇÃO (PLACEHOLDER - tabela não existe ainda)
CREATE OR REPLACE VIEW vw_semantica_satisfacao AS
SELECT 
    0 as dd_order_id,
    0 as review_score, 
    0 as flag_tem_comentario,
    '' as customer_state,
    '' as categoria
WHERE FALSE;
"""

print("Executando o DDL das Views no PostgreSQL...")
with engine.begin() as conn:
    conn.execute(text(views_sql))
print("Sucesso! Camada semântica criada.")

Executando o DDL das Views no PostgreSQL...
Sucesso! Camada semântica criada.

#### Passo 2: Validação Analítica (Respondendo ao README.md)
Consome Views para responder às 12 perguntas de negócio definidas no projeto, estruturadas nas 4 Perspectivas Estratégicas.

In [4]:
print("================ 1. INTELIGÊNCIA DE CLIENTES ================\n")

print("Pergunta 1.1: Comportamento de Recompra e Ticket Médio")
q_recompra = """
WITH cliente_compras AS (
    SELECT 
        bk_customer_unique_id,
        COUNT(DISTINCT dd_order_id) AS qtd_compras,
        AVG(valor_total_item) AS ticket_medio
    FROM vw_semantica_vendas
    GROUP BY 1
)
SELECT 
    CASE WHEN qtd_compras > 1 THEN 'Recorrente (Mais de 1 compra)' ELSE 'Compra Única' END AS perfil,
    COUNT(*) AS qtd_clientes,
    ROUND(AVG(ticket_medio), 2) AS ticket_medio_geral
FROM cliente_compras
GROUP BY 1;
"""
display(pd.read_sql(q_recompra, engine))

print("\nPergunta 1.2: Top Clientes (Curva ABC Básica - Top 5)")
q_top_clientes = """
SELECT bk_customer_unique_id AS id_cliente, customer_state AS estado, SUM(valor_total_item) AS receita_total
FROM vw_semantica_vendas
GROUP BY 1, 2 ORDER BY 3 DESC LIMIT 5;
"""
display(pd.read_sql(q_top_clientes, engine))

print("\nPergunta 1.3: Região com Maior Receita")
q_regiao = """
SELECT 
    customer_state AS estado, 
    COUNT(DISTINCT dd_order_id) AS qtd_pedidos,
    ROUND(SUM(valor_total_item), 2) AS receita_total
FROM vw_semantica_vendas
GROUP BY 1 ORDER BY 3 DESC LIMIT 10;
"""
display(pd.read_sql(q_regiao, engine))

================ 1. INTELIGÊNCIA DE CLIENTES ================

Pergunta 1.1: Comportamento de Recompra e Ticket Médio

                          perfil  qtd_clientes  ticket_medio_geral
0                   Compra Única         92507              147.40
1  Recorrente (Mais de 1 compra)          2913              126.01

Pergunta 1.2: Top Clientes (Curva ABC Básica - Top 5)

                         id_cliente estado  receita_total
0  0a0a92112bd4c708ca5fde585afaa872     RJ       13664.08
1  8af7ac63b2efbcbd88e5b11505e8098a     MT       13281.71
2  c4b224d2c784bae11ae98b6ae9f2454c     SP       11111.40
3  85963fd37bfd387aa6d915d8a1065486     SP       10553.28
4  be74c431147c32ab2d7c7cef5e4a995f     RS       10055.22

Pergunta 1.3: Região com Maior Receita

  estado  qtd_pedidos  receita_total
0     SP        41374     6235556.48
1     RJ        12761     2246749.91
2     MG        11551     1929121.51
3     RS         5432      934308.23
4     PR         4998      832125.57
5     BA         3358      650223.81
6     SC         3612      632034.31
7     GO         2009      369668.27
8     DF         2125      367607.99
9     ES         2024      336305.29

In [5]:
print("================ 3. ANÁLISE DE PREÇO E RECEITA ================\n")

print("Pergunta 3.1: Distribuição de Valores de Itens")
q_preco = """
SELECT 
    CASE WHEN preco_item <= 50 THEN 'Até R$ 50'
         WHEN preco_item <= 100 THEN 'R$ 50-100'
         WHEN preco_item <= 200 THEN 'R$ 100-200'
         WHEN preco_item <= 500 THEN 'R$ 200-500'
         ELSE 'Acima de R$ 500' END AS faixa_preco,
    COUNT(*) AS qtd_itens,
    ROUND(AVG(preco_item), 2) AS preco_medio,
    ROUND(SUM(valor_total_item), 2) AS receita_total
FROM vw_semantica_vendas
WHERE preco_item > 0
GROUP BY 1 ORDER BY 4 DESC;
"""
display(pd.read_sql(q_preco, engine))

print("\nPergunta 3.2: Receita Mensal")
q_receita_mes = """
SELECT ano, mes, ROUND(SUM(valor_total_item), 2) AS receita_total
FROM vw_semantica_vendas
GROUP BY 1, 2 ORDER BY 1, 2;
"""
display(pd.read_sql(q_receita_mes, engine))

print("\nPergunta 3.3: Impacto do Frete na Receita")
q_impacto_frete = """
SELECT 
    ROUND(SUM(valor_total_item), 2) AS receita_bruta,
    ROUND(SUM(valor_frete), 2) AS frete_total,
    ROUND(SUM(valor_total_item) - SUM(valor_frete), 2) AS receita_liquida,
    ROUND((SUM(valor_frete) / SUM(valor_total_item)) * 100, 2) AS percentual_frete
FROM vw_semantica_vendas;
"""
display(pd.read_sql(q_impacto_frete, engine))

================ 3. ANÁLISE DE PREÇO E RECEITA ================

Pergunta 3.1: Distribuição de Valores de Itens

       faixa_preco  qtd_itens  preco_medio  receita_total
0       R$ 100-200      28036       143.63     4677615.88
1       R$ 200-500      10668       297.88     3500471.92
2  Acima de R$ 500       3392       928.43     3310047.36
3        R$ 50-100      34862        75.15     3243358.31
4        Até R$ 50      41352        31.44     1912237.83

Pergunta 3.2: Receita Mensal

     ano  mes  receita_total
0   2016    9         354.75
1   2016   10       58730.85
2   2016   12          19.62
3   2017    1      148030.11
4   2017    2      303648.31
5   2017    3      459778.64
6   2017    4      449707.81
7   2017    5      634762.22
8   2017    6      531052.06
9   2017    7      631341.57
10  2017    8      706168.95
11  2017    9      767325.70
12  2017   10      808911.33
13  2017   11     1232074.30
14  2017   12      898427.92
15  2018    1     1158742.84
16  2018    2     1039011.65
17  2018    3     1209080.30
18  2018    4     1201102.21
19  2018    5     1193204.98
20  2018    6     1075753.44
21  2018    7     1097939.54
22  2018    8     1038395.74
23  2018    9         166.46

Pergunta 3.3: Impacto do Frete na Receita

   receita_bruta  frete_total  receita_liquida  percentual_frete
0     16643731.3   2370031.65      14273699.65             14.24

In [6]:
print("================ 4. ANÁLISE DE CATEGORIAS E MERCADO ================\n")

print("Pergunta 4.1: Categorias com Maior Volume de Vendas")
q_categorias = """
SELECT 
    categoria,
    COUNT(DISTINCT dd_order_id) AS qtd_pedidos,
    COUNT(dd_order_item_id) AS qtd_itens,
    ROUND(SUM(valor_total_item), 2) AS receita_total,
    ROUND(AVG(valor_total_item), 2) AS ticket_medio
FROM vw_semantica_vendas
WHERE categoria IS NOT NULL
GROUP BY 1 ORDER BY 4 DESC LIMIT 10;
"""
display(pd.read_sql(q_categorias, engine))

print("\nPergunta 4.2: Análise de Frete por Categoria")
q_frete = """
SELECT 
    categoria,
    COUNT(dd_order_item_id) AS qtd_itens,
    ROUND(AVG(valor_frete), 2) AS frete_medio,
    ROUND(AVG(valor_frete / NULLIF(valor_total_item, 0)) * 100, 2) AS frete_percentual
FROM vw_semantica_vendas
WHERE categoria IS NOT NULL AND valor_total_item > 0
GROUP BY 1 ORDER BY 4 DESC LIMIT 10;
"""
display(pd.read_sql(q_frete, engine))

print("\nPergunta 4.3: Análise Temporal de Vendas (Por Mês)")
q_temporal = """
SELECT 
    ano, mes,
    COUNT(DISTINCT dd_order_id) AS qtd_pedidos,
    COUNT(dd_order_item_id) AS qtd_itens,
    ROUND(SUM(valor_total_item), 2) AS receita_total
FROM vw_semantica_vendas
GROUP BY 1, 2 ORDER BY 1, 2;
"""
display(pd.read_sql(q_temporal, engine))

================ 4. ANÁLISE DE CATEGORIAS E MERCADO ================

Pergunta 4.1: Categorias com Maior Volume de Vendas

               categoria  qtd_pedidos  qtd_itens  receita_total  ticket_medio
0          health_beauty         8836      10032     1491397.76        148.66
1          watches_gifts         5624       6213     1358845.59        218.71
2         bed_bath_table         9417      11988     1327662.02        110.75
3         sports_leisure         7720       9004     1205197.85        133.85
4  computers_accessories         6689       8150     1104362.03        135.50
5        furniture_decor         6449       8832      955367.22        108.17
6             housewares         5884       7380      823623.50        111.60
7             cool_stuff         3632       3999      752702.21        188.22
8                   auto         3897       4400      714431.95        162.37
9           garden_tools         3518       4590      625387.31        136.25

Pergunta 4.2: Análise de Frete por Categoria

                           categoria  qtd_itens  frete_medio  frete_percentual
0                     home_comfort_2         31        13.59             45.86
1                       dvds_blu_ray         71        20.15             39.23
2                        electronics       2846        16.85             35.58
3                 christmas_supplies        155        20.99             34.03
4                            flowers         33        14.81             33.91
5                         food_drink        291        16.41             30.30
6                          telephony       4726        15.72             29.97
7  furniture_mattress_and_upholstery         41        41.77             29.56
8                diapers_and_hygiene         39        14.71             28.52
9             signaling_and_security        201        32.52             28.49

Pergunta 4.3: Análise Temporal de Vendas (Por Mês)

     ano  mes  qtd_pedidos  qtd_itens  receita_total
0   2016    9            3          6         354.75
1   2016   10          308        385       58730.85
2   2016   12            1          1          19.62
3   2017    1          789       1023      148030.11
4   2017    2         1733       2073      303648.31
5   2017    3         2641       3201      459778.64
6   2017    4         2391       2864      449707.81
7   2017    5         3660       4445      634762.22
8   2017    6         3217       3822      531052.06
9   2017    7         3969       4887      631341.57
10  2017    8         4293       5224      706168.95
11  2017    9         4243       5136      767325.70
12  2017   10         4568       5617      808911.33
13  2017   11         7451       9096     1232074.30
14  2017   12         5624       6593      898427.92
15  2018    1         7220       8603     1158742.84
16  2018    2         6694       8022     1039011.65
17  2018    3         7188       8592     1209080.30
18  2018    4         6934       8272     1201102.21
19  2018    5         6853       8231     1193204.98
20  2018    6         6160       7396     1075753.44
21  2018    7         6273       7356     1097939.54
22  2018    8         6452       7464     1038395.74
23  2018    9            1          1         166.46

In [7]:
print("================ 5. RESUMO EXECUTIVO ================\n")

print("Pergunta 5.1: Estatísticas Gerais do Dataset")
q_resumo = """
SELECT 
    COUNT(DISTINCT dd_order_id) AS qtd_pedidos,
    COUNT(DISTINCT bk_customer_unique_id) AS qtd_clientes,
    COUNT(dd_order_item_id) AS qtd_itens,
    ROUND(SUM(valor_total_item), 2) AS receita_total,
    ROUND(SUM(valor_frete), 2) AS frete_total,
    ROUND(AVG(valor_total_item), 2) AS ticket_medio,
    ROUND(MIN(valor_total_item), 2) AS valor_minimo,
    ROUND(MAX(valor_total_item), 2) AS valor_maximo
FROM vw_semantica_vendas;
"""
display(pd.read_sql(q_resumo, engine))

print("\nPergunta 5.2: Top 5 Categorias por Faturamento")
q_top_cat = """
SELECT 
    categoria,
    COUNT(dd_order_item_id) AS qtd_itens,
    ROUND(SUM(valor_total_item), 2) AS faturamento,
    ROUND(AVG(valor_total_item), 2) AS ticket_medio
FROM vw_semantica_vendas
WHERE categoria IS NOT NULL
GROUP BY 1 ORDER BY 3 DESC LIMIT 5;
"""
display(pd.read_sql(q_top_cat, engine))

print("\nPergunta 5.3: Resumo por Estado (Top 10)")
q_estados = """
SELECT 
    customer_state AS estado,
    COUNT(DISTINCT dd_order_id) AS qtd_pedidos,
    ROUND(SUM(valor_total_item), 2) AS receita_total,
    ROUND(AVG(valor_total_item), 2) AS ticket_medio
FROM vw_semantica_vendas
GROUP BY 1 ORDER BY 3 DESC LIMIT 10;
"""
display(pd.read_sql(q_estados, engine))

================ 5. RESUMO EXECUTIVO ================

Pergunta 5.1: Estatísticas Gerais do Dataset

,qtd_pedidos,qtd_clientes,qtd_itens,receita_total,frete_total,ticket_medio,valor_minimo,valor_maximo
0,98666,95420,118310,16643731.3,2370031.65,140.68,6.08,6929.31

Pergunta 5.2: Top 5 Categorias por Faturamento

               categoria  qtd_itens  faturamento  ticket_medio
0          health_beauty      10032   1491397.76        148.66
1          watches_gifts       6213   1358845.59        218.71
2         bed_bath_table      11988   1327662.02        110.75
3         sports_leisure       9004   1205197.85        133.85
4  computers_accessories       8150   1104362.03        135.50

Pergunta 5.3: Resumo por Estado (Top 10)

  estado  qtd_pedidos  receita_total  ticket_medio
0     SP        41374     6235556.48        125.05
1     RJ        12761     2246749.91        145.68
2     MG        11551     1929121.51        140.55
3     RS         5432      934308.23        142.90
4     PR         4998      832125.57        138.94
5     BA         3358      650223.81        159.80
6     SC         3612      632034.31        146.41
7     GO         2009      369668.27        150.39
8     DF         2125      367607.99        147.10
9     ES         2024      336305.29        143.11